/**
 * Report Card Generator
 * Generates PDF report cards for students
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface StudentInfo {
    name: string;
    className: string;
    session: string;
    term: string;
    admissionNumber?: string;
}

interface ResultRow {
    subject: string;
    caScore: number;
    examScore: number;
    total: number;
    grade: string;
    remark: string;
}

interface ReportCardData {
    student: StudentInfo;
    results: ResultRow[];
    cgpa: number;
    position: number;
    totalStudents: number;
    attendance: {
        present: number;
        absent: number;
        total: number;
    };
    remarks?: {
        classTeacher?: string;
        principal?: string;
    };
}

export async function generateReportCard(data: ReportCardData): Promise<Blob> {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // School Header
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('ADVANCED SCHOOL MANAGEMENT SYSTEM', pageWidth / 2, 20, { align: 'center' });

    doc.setFontSize(16);
    doc.text('STUDENT REPORT CARD', pageWidth / 2, 30, { align: 'center' });

    // Student Information
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    const studentInfoY = 45;
    doc.text(`Name: ${data.student.name}`, 20, studentInfoY);
    doc.text(`Class: ${data.student.className}`, 20, studentInfoY + 7);
    doc.text(`Session: ${data.student.session}`, 120, studentInfoY);
    doc.text(`Term: ${data.student.term}`, 120, studentInfoY + 7);

    if (data.student.admissionNumber) {
        doc.text(`Admission No: ${data.student.admissionNumber}`, 20, studentInfoY + 14);
    }

    // Results Table
    const tableStartY = studentInfoY + 25;

    autoTable(doc, {
        startY: tableStartY,
        head: [['Subject', 'CA (40)', 'Exam (60)', 'Total (100)', 'Grade', 'Remark']],
        body: data.results.map(r => [
            r.subject,
            r.caScore.toFixed(1),
            r.examScore.toFixed(1),
            r.total.toFixed(1),
            r.grade,
            r.remark
        ]),
        theme: 'grid',
        headStyles: {
            fillColor: [41, 128, 185],
            textColor: 255,
            fontStyle: 'bold',
            halign: 'center'
        },
        bodyStyles: {
            halign: 'center'
        },
        columnStyles: {
            0: { halign: 'left', cellWidth: 50 }
        }
    });

    // Summary Section
    const finalY = (doc as any).lastAutoTable.finalY + 15;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('SUMMARY', 20, finalY);

    doc.setFont('helvetica', 'normal');
    doc.text(`CGPA: ${data.cgpa.toFixed(2)}`, 20, finalY + 8);
    doc.text(`Position: ${data.position} out of ${data.totalStudents}`, 20, finalY + 15);
    doc.text(`Attendance: ${data.attendance.present}/${data.attendance.total} days present`, 20, finalY + 22);

    // Remarks Section
    if (data.remarks) {
        const remarksY = finalY + 35;

        doc.setFont('helvetica', 'bold');
        doc.text('REMARKS', 20, remarksY);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);

        if (data.remarks.classTeacher) {
            doc.text('Class Teacher:', 20, remarksY + 8);
            doc.text(data.remarks.classTeacher, 20, remarksY + 13, { maxWidth: 170 });
        }

        if (data.remarks.principal) {
            doc.text('Principal:', 20, remarksY + 25);
            doc.text(data.remarks.principal, 20, remarksY + 30, { maxWidth: 170 });
        }
    }

    // Footer
    const footerY = doc.internal.pageSize.getHeight() - 20;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.text('Generated by Advanced School Management System', pageWidth / 2, footerY, { align: 'center' });
    doc.text(new Date().toLocaleDateString(), pageWidth / 2, footerY + 5, { align: 'center' });

    // Return as Blob
    return doc.output('blob');
}

/**
 * Download report card as PDF
 */
export function downloadReportCard(blob: Blob, studentName: string, term: string) {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${studentName.replace(/\s+/g, '_')}_${term}_Report.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
